-- =====================================================================
-- Generated by skill expose-data-entity on 2026-05-15
-- Target server:    192.168.50.86
-- Target database:  IE_MONITOR
-- Scope:            whole database (db_datareader)
-- =====================================================================
-- Ejecutar como `sa` o un admin con permiso en master + IE_MONITOR.
-- Cada bloque por separado (o asegurar que los GO procesen).
-- =====================================================================

-- 1. LOGIN a nivel servidor — primera vez de mcp_reader en este host.
--    Reemplazar <REEMPLAZAR_POR_PASSWORD_REAL> antes de ejecutar.
--    La password real vive solo en deploy/.env (gitignored) — NO commitear aqui.
USE master;
GO

IF NOT EXISTS (SELECT 1 FROM sys.server_principals WHERE name = 'mcp_reader')
    CREATE LOGIN mcp_reader WITH PASSWORD = '<REEMPLAZAR_POR_PASSWORD_REAL>';
GO


-- 2. USER a nivel BD IE_MONITOR
USE IE_MONITOR;
GO

IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = 'mcp_reader')
    CREATE USER mcp_reader FOR LOGIN mcp_reader;
GO


-- 3. Permisos — toda la BD en lectura
--    db_datareader otorga SELECT sobre TODAS las tablas/vistas presentes y futuras.
--    Si en el futuro se prefiere whitelist explicita, revocar este rol y dar
--    GRANT SELECT por objeto.
EXEC sp_addrolemember 'db_datareader', 'mcp_reader';
GO


-- 4. Verificacion: debe listar el rol y (vacio aqui es OK, db_datareader es
--    permiso a nivel rol, no a nivel objeto)
USE IE_MONITOR;
SELECT
    DB_NAME()      AS database_name,
    pr.name        AS user_name,
    dp.name        AS role_name
FROM sys.database_role_members rm
JOIN sys.database_principals pr ON rm.member_principal_id = pr.principal_id
JOIN sys.database_principals dp ON rm.role_principal_id   = dp.principal_id
WHERE pr.name = 'mcp_reader';


-- 5. Descubrimiento de objetos a exponer (correr y pegar resultado al agente
--    para que genere los entity blocks en dab-config.monitor.json):
USE IE_MONITOR;
SELECT s.name AS schema_name, o.name AS object_name, o.type_desc
FROM sys.objects o
JOIN sys.schemas s ON o.schema_id = s.schema_id
WHERE o.type IN ('U','V')      -- U=tabla, V=vista
ORDER BY s.name, o.name;


-- 6. (Opcional) Descripciones a nivel tabla si existen en sys.extended_properties:
USE IE_MONITOR;
SELECT s.name AS schema_name, o.name AS object_name,
       CAST(ep.value AS NVARCHAR(MAX)) AS description
FROM sys.objects o
JOIN sys.schemas s ON o.schema_id = s.schema_id
LEFT JOIN sys.extended_properties ep
    ON ep.major_id = o.object_id
   AND ep.minor_id = 0
   AND ep.name = 'MS_Description'
WHERE o.type IN ('U','V')
  AND ep.value IS NOT NULL
ORDER BY s.name, o.name;
