-- =====================================================================
-- Generated by skill expose-data-entity on 2026-06-05
-- Target server:    sqlcorp.ie
-- Target database:  INTRANET
-- Scope:            whole database (read-only, db_datareader)
--                   - mcp_reader: SOLO LECTURA sobre todas las tablas/vistas
-- =====================================================================
-- Ejecutar como `sa` o un admin con permiso en master + INTRANET.
-- Procesar cada bloque (respetar los GO).
--
-- NOTA: el LOGIN mcp_reader YA EXISTE en sqlcorp.ie (creado por
-- grants-monitor.sql). Este script solo crea el USER en INTRANET y le
-- asigna db_datareader. Si por alguna razon el login no existe, el
-- bloque 1 lo crea (reemplazar el placeholder de password).
-- La password real vive solo en deploy/.env (gitignored) — NO commitear aqui.
-- =====================================================================

-- 1. LOGIN a nivel servidor (solo si NO existe ya en este host)
USE master;
GO

IF NOT EXISTS (SELECT 1 FROM sys.server_principals WHERE name = 'mcp_reader')
    CREATE LOGIN mcp_reader WITH PASSWORD = '<REEMPLAZAR_POR_PASSWORD_REAL>';
GO

-- 2. USER a nivel BD INTRANET
USE INTRANET;
GO

IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = 'mcp_reader')
    CREATE USER mcp_reader FOR LOGIN mcp_reader;
GO

-- 3. Rol read-only sobre TODA la BD (presentes y futuras tablas)
EXEC sp_addrolemember 'db_datareader', 'mcp_reader';
GO

-- =====================================================================
-- VERIFICACION
-- =====================================================================
USE INTRANET;
SELECT
    DB_NAME() AS database_name,
    pr.name   AS user_name,
    dp.name   AS role_name
FROM sys.database_role_members rm
JOIN sys.database_principals pr ON rm.member_principal_id = pr.principal_id
JOIN sys.database_principals dp ON rm.role_principal_id   = dp.principal_id
WHERE pr.name = 'mcp_reader'
ORDER BY dp.name;

-- =====================================================================
-- DESCUBRIMIENTO (opcional) — listado de objetos en la BD
-- =====================================================================
USE INTRANET;
SELECT s.name AS schema_name, o.name AS object_name, o.type_desc
FROM sys.objects o
JOIN sys.schemas s ON o.schema_id = s.schema_id
WHERE o.type IN ('U','V')
ORDER BY s.name, o.name;
