-- =====================================================================
-- Generated by skill expose-data-entity on 2026-05-15
-- Target server:    192.168.50.86
-- Target database:  IE_MONITOR
-- Scope:            whole database
--                   - mcp_reader: read-only (db_datareader)
--                   - mcp_writer: read + write (db_datareader + db_datawriter)
-- =====================================================================
-- Ejecutar como `sa` o un admin con permiso en master + IE_MONITOR.
-- Cada bloque por separado (o asegurar que los GO procesen).
-- =====================================================================

-- =====================================================================
-- BLOQUE A: usuario de SOLO LECTURA (mcp_reader)
-- =====================================================================

-- A.1 LOGIN a nivel servidor — primera vez de mcp_reader en este host.
--     Reemplazar <REEMPLAZAR_POR_PASSWORD_REAL> antes de ejecutar.
--     La password real vive solo en deploy/.env (gitignored) — NO commitear aqui.
USE master;
GO

IF NOT EXISTS (SELECT 1 FROM sys.server_principals WHERE name = 'mcp_reader')
    CREATE LOGIN mcp_reader WITH PASSWORD = '<REEMPLAZAR_POR_PASSWORD_REAL>';
GO

-- A.2 USER a nivel BD
USE IE_MONITOR;
GO

IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = 'mcp_reader')
    CREATE USER mcp_reader FOR LOGIN mcp_reader;
GO

-- A.3 Rol read-only
EXEC sp_addrolemember 'db_datareader', 'mcp_reader';
GO


-- =====================================================================
-- BLOQUE B: usuario de LECTURA + ESCRITURA (mcp_writer)
-- =====================================================================
-- mcp_writer puede leer + insertar + actualizar + borrar en TODAS las
-- tablas presentes y futuras de IE_MONITOR. Lo usa DAB cuando el
-- connection string apunta a este user (ver MSSQL_MONITOR_CONN en .env).
-- Si se prefiere whitelist por tabla en el futuro, revocar los roles
-- db_data*writer y reemplazar por GRANT INSERT, UPDATE, DELETE explicitos.

-- B.1 LOGIN
USE master;
GO

IF NOT EXISTS (SELECT 1 FROM sys.server_principals WHERE name = 'mcp_writer')
    CREATE LOGIN mcp_writer WITH PASSWORD = '<REEMPLAZAR_POR_PASSWORD_REAL>';
GO

-- B.2 USER
USE IE_MONITOR;
GO

IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = 'mcp_writer')
    CREATE USER mcp_writer FOR LOGIN mcp_writer;
GO

-- B.3 Roles read + write
EXEC sp_addrolemember 'db_datareader', 'mcp_writer';
EXEC sp_addrolemember 'db_datawriter', 'mcp_writer';
GO


-- =====================================================================
-- VERIFICACION
-- =====================================================================
USE IE_MONITOR;
SELECT
    DB_NAME()      AS database_name,
    pr.name        AS user_name,
    dp.name        AS role_name
FROM sys.database_role_members rm
JOIN sys.database_principals pr ON rm.member_principal_id = pr.principal_id
JOIN sys.database_principals dp ON rm.role_principal_id   = dp.principal_id
WHERE pr.name IN ('mcp_reader', 'mcp_writer')
ORDER BY pr.name, dp.name;


-- =====================================================================
-- DESCUBRIMIENTO (opcional) — listado de objetos en la BD
-- =====================================================================
USE IE_MONITOR;
SELECT s.name AS schema_name, o.name AS object_name, o.type_desc
FROM sys.objects o
JOIN sys.schemas s ON o.schema_id = s.schema_id
WHERE o.type IN ('U','V')
ORDER BY s.name, o.name;
